# Generated by Django 5.0.4 on 2024-06-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0003_alter_usuario_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='modulo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
